import { Types } from 'mongoose'; // Only if using Mongoose ObjectIds directly in base interfaces for references
                                 // If these are purely DTOs before DB, string might be used for IDs.
                                 // For consistency with IProductDocument, using Types.ObjectId is fine.


// Reusable Enums & Basic Types for Products

export type ProductStatus =
  | "draft"          // Product is being worked on, not visible to customers
  | "pending_review" // Submitted for admin approval (if your workflow requires this)
  | "active"         // Live and purchasable/visible on the storefront
  | "archived"       // No longer sold, kept for admin records, not visible to customers
  | "rejected";      // Admin rejected the product submission

export type ProductVisibility =
  | "public"         // Visible to everyone on the storefront
  | "hidden"         // Not listed in categories/search, but accessible via direct link (e.g., for previews)
  | "private";       // Only visible to specific user groups or admins (less common for general products)

export type StockStatus =
  | "in_stock"
  | "out_of_stock"
  | "backorder"    // Can be ordered, will ship when stock is available
  | "pre_order";   // Available for pre-order before official release/availability

export interface IDimensions {
  length?: number;
  width?: number;
  height?: number;
  unit?: "cm" | "in" | "mm" | "m" | "ft" | "yd"; 
}


// Product Attribute & Variation Structure

export interface IProductAttributeOption {
  attributeId: Types.ObjectId; // FK to your Attributes collection (e.g., ID for "Color")
  attributeName: string;       // Denormalized: "Color"
  optionId: Types.ObjectId;    // FK to your AttributeOptions collection (e.g., ID for "Red")
  optionValue: string;         // Denormalized: "Red"
  optionSwatchValue?: string;   // Optional: e.g., "#FF0000" for color, or URL for a pattern image
}


 // Defines a specific, purchasable version of a product.
 
export interface IProductVariation {
  _id?: Types.ObjectId; // Auto-generated by DB, optional on creation payload

  sku?: string;         // Stock Keeping Unit for THIS variation. Should be unique across all variations if used.
  price: number;        // The actual selling price of this variation.
  salePrice?: number;   // Optional discounted price for this variation.
  inventory: number;    // Current stock level for this variation.
  stockStatus: StockStatus; // Stock status of this variation.

  // The combination of attribute options that uniquely identifies this variation.
  // e.g., [{attrId: "colorId", optionId: "redId"}, {attrId: "sizeId", optionId: "largeId"}]
  attributeOptions: IProductAttributeOption[];

  imageUrls?: string[];   // Images specific to this variation (e.g., image of the red shirt).
                          // If empty, frontend might fall back to main product images.
  mainVariationImageIndex?: number; // Index in imageUrls to use as the primary for this variation.

  weight?: number;        // Weight of this variation (if different from others).
  weightUnit?: "kg" | "g" | "lb" | "oz";
  dimensions?: IDimensions; // Dimensions of this variation.

  barcode?: string;       // e.g., UPC, EAN, ISBN, GTIN for this specific variation.
  costPrice?: number;     // (Typically Admin-only) Cost of this variation, for profit calculation.
  lowStockThreshold?: number; // Threshold to trigger "low stock" warnings for this variation.

  isActive?: boolean;     // Can this specific variation be purchased? Defaults to true if not set.
                          // Allows disabling a single variation (e.g., "Blue Small" is discontinued).
}


export interface IProduct {
  _id?: Types.ObjectId; 

  name: string;          // Primary product name, e.g., "Organic Cotton T-Shirt"
  slug?: string;         // URL-friendly version of the name, auto-generated, unique.
  description?: string;  // Detailed product description (supports HTML/Markdown if needed).
  shortDescription?: string; // A brief summary for product listings or previews.

  // These prices can act as a display default or "starting from" price if variations have different prices.
  // For products with a single variation, this might be redundant if variation has price.
  // Consider if truly needed if all purchasable items are variations with their own prices.
  // basePrice?: number;
  // baseSalePrice?: number;
  currency: string;      // e.g., "USD", "EUR". Should be consistent across product/variations for simplicity initially.

  categoryId: Types.ObjectId; // FK to your Categories collection.
  // categoryPath?: string[]; // Denormalized array of ancestor category names/slugs for breadcrumbs.

  brandId?: Types.ObjectId;    // FK to your Brands collection (optional).
  // brandName?: string;       // Denormalized brand name.

  tags?: string[];           // Searchable tags or keywords.

  // Main/default images for the product. The first is often the primary.
  // Variations can have their own `imageUrls` which would override these for that specific variation.
  imageUrls: string[];
  mainProductImageIndex?: number; // Index of the primary image in `imageUrls`.

  sellerType: "individual_seller" | "vendor";
  sellerId: Types.ObjectId;   // FK to the Seller or Vendor collection.

  status: ProductStatus;        // Overall status of the product listing.
  visibility: ProductVisibility;// Controls visibility on the storefront.

  // All purchasable versions of the product.
  // For a "simple" product, this array will contain one IProductVariation object.
  // This variation will hold the SKU, price, inventory for that simple product.
  // Its `attributeOptions` array would be empty.
  variations: IProductVariation[];

  // SEO related fields
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string[];     // Can be an array of strings

  // Shipping related (can be default if not overridden by variations)
  defaultWeight?: number;
  defaultWeightUnit?: "kg" | "g" | "lb" | "oz";
  defaultDimensions?: IDimensions;
  isShippingRequired?: boolean; // Default true, false for digital goods.

  // Compliance & Restrictions
  isHazardousMaterial?: boolean;
  isAgeRestricted?: boolean;
  ageRestrictionMinimum?: number; // e.g., 18, 21

  // Additional settings
  allowReviews?: boolean;        // Can customers leave reviews for this product? (default true)
  averageRating?: number;      // Denormalized, updated when reviews are added/changed.
  reviewCount?: number;        // Denormalized.
  // featured?: boolean;        // To mark product as featured on homepage etc.
  // sortOrder?: number;        // For custom sorting within categories.

  // Auditing & Timestamps
  createdBy: Types.ObjectId;   // User ID (Admin, Seller, or Vendor staff)
  updatedBy?: Types.ObjectId;  // User ID
  reviewedBy?: Types.ObjectId; // Admin User ID if review process exists
  reviewComment?: string;    // Admin's comment if rejected or requires changes
  reviewedAt?: Date;
  publishedAt?: Date;        // Date when status changed to 'active' first time or from 'draft'
  createdAt?: Date;          // Auto-managed by Mongoose/DB
  updatedAt?: Date;          // Auto-managed by Mongoose/DB
}



export interface IProductListItemData extends Pick<
  IProduct,
  '_id' | 'name' | 'slug' | 'currency' | 'imageUrls' | 'status' | 'visibility' | 'tags' | 'sellerType' | 'sellerId'
> {
  // Derived or essential display fields
  mainImageUrl: string; // Usually the first from IProduct.imageUrls or a specific thumbnail
  displayPrice: number; // Could be basePrice, or lowest variation price, or salePrice if active
  displaySalePrice?: number;
  isOnSale: boolean;
  stockStatus: StockStatus; // Overall or primary variation's stock status for display
  categoryName?: string;
  brandName?: string;
  averageRating?: number;
  // Link to the product detail page
  viewLink: string;
}


/**
 * Mongoose Document interface for a Product.
 * Extends IProduct and the base Mongoose Document type.
 */
export interface IProductDocument extends IProduct, Document {
  _id: Types.ObjectId; // Ensure _id is strongly typed and required for DB documents
  // Add any Mongoose virtuals or instance methods specific to your Product schema here
  // e.g., populateVariations(): Promise<void>;
  // e.g., getEffectivePrice(): number;
}



// Data Transfer Objects (DTOs) for API Payloads (Example)


/**
 * Payload for creating a new product.
 * Variations are often created alongside the main product.
 */
export type CreateProductDTO = Omit<IProduct, '_id' | 'slug' | 'averageRating' | 'reviewCount' | 'publishedAt' | 'createdAt' | 'updatedAt' | 'reviewedBy' | 'reviewedAt' | 'updatedBy'> & {
  variations: Array<Omit<IProductVariation, '_id'>>; // Variations don't have _id on creation
};


/**
 * Payload for updating an existing product.
 * Most fields are optional. Variations might be updated in bulk or via separate endpoints.
 */
export type UpdateProductDTO = Partial<Omit<IProduct, '_id' | 'slug' | 'sellerId' | 'sellerType' | 'createdBy' | 'createdAt' | 'updatedAt' >> & {
  updatedBy: Types.ObjectId; // Always require who updated it
  // How variations are updated needs careful consideration:
  // Option A: Send the full list of variations, backend diffs/replaces.
  // variations?: Array<Partial<IProductVariation> & { _id?: Types.ObjectId }>; // Allows adding new, updating existing
  // Option B: Separate endpoints for managing variations (CRUD for variations). This is often cleaner.
};