// This file should live in your frontend's interfaces or types directory.
// e.g., src/interfaces/Product/product.interfaces.ts

// It's common practice to have a way to represent ObjectIDs on the frontend.
// This can be a simple string or a more complex object depending on your needs.
// For simplicity and compatibility, we'll define it as a string,
// as that's how it will often be used in URLs and component props.
export type ObjectId = string;

// Reusable Enums & Basic Types for Products

export type ProductStatus =
  | "draft" // Product is being worked on, not visible to customers
  | "pending_review" // Submitted for admin approval
  | "active" // Live and purchasable/visible on the storefront
  | "archived" // No longer sold, kept for records, not visible
  | "rejected"; // Admin rejected the product submission

export type ProductVisibility =
  | "public" // Visible to everyone on the storefront
  | "hidden" // Not listed, but accessible via direct link
  | "private"; // Only visible to specific user groups or admins

export type StockStatus =
  | "in_stock"
  | "out_of_stock"
  | "backorder" // Can be ordered, will ship when available
  | "pre_order"; // Available for pre-order before release

export interface IDimensions {
  length?: number;
  width?: number;
  height?: number;
  unit?: "cm" | "in" | "mm" | "m" | "ft" | "yd";
}

// Product Attribute & Variation Structure

export interface IProductAttributeOption {
  attributeId: ObjectId; // FK to Attributes collection (e.g., ID for "Color")
  attributeName: string; // Denormalized: "Color"
  optionId: ObjectId; // FK to AttributeOptions collection (e.g., ID for "Red")
  optionValue: string; // Denormalized: "Red"
  optionSwatchValue?: string; // Optional: e.g., "#FF0000" for color
}

/**
 * Defines a specific, purchasable version of a product.
 */
export interface IProductVariation {
  _id?: ObjectId; // Auto-generated by DB
  sku?: string; // Stock Keeping Unit for THIS variation
  price: number; // The actual selling price of this variation
  salePrice?: number; // Optional discounted price
  inventory: number; // Current stock level
  stockStatus: StockStatus; // Stock status of this variation
  attributeOptions: IProductAttributeOption[]; // The combination that identifies this variation
  imageUrls?: string[]; // Images specific to this variation
  mainVariationImageIndex?: number; // Index of the primary image in `imageUrls`
  weight?: number;
  weightUnit?: "kg" | "g" | "lb" | "oz";
  dimensions?: IDimensions;
  barcode?: string; // e.g., UPC, EAN for this specific variation
  costPrice?: number; // (Admin-only) Cost of this variation
  lowStockThreshold?: number; // Threshold for "low stock" warnings
  isActive?: boolean; // Can this specific variation be purchased?
}

/**
 * The core Product interface, representing the full product document in the database.
 */
export interface IProduct {
  _id?: ObjectId;
  name: string;
  slug?: string; // URL-friendly name, auto-generated
  description?: string;
  shortDescription?: string;
  basePrice?: number; // "Starting from" price
  baseSalePrice?: number;
  currency: string; // e.g., "USD", "EUR"
  categoryId: ObjectId; // FK to Categories collection
  brandId?: ObjectId; // FK to Brands collection
  tags?: string[]; // Searchable tags
  imageUrls: string[]; // Main product images
  mainProductImageIndex?: number;
  sellerType: "individual_seller" | "vendor";
  sellerId: ObjectId; // FK to the Seller or Vendor
  status: ProductStatus;
  visibility: ProductVisibility;
  variations: IProductVariation[]; // All purchasable versions of the product
  // SEO fields
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string[];
  // Default shipping fields
  defaultWeight?: number;
  defaultWeightUnit?: "kg" | "g" | "lb" | "oz";
  defaultDimensions?: IDimensions;
  isShippingRequired?: boolean;
  // Compliance & Restrictions
  isHazardousMaterial?: boolean;
  isAgeRestricted?: boolean;
  ageRestrictionMinimum?: number;
  // Additional settings
  allowReviews?: boolean;
  averageRating?: number; // Denormalized, updated via reviews
  reviewCount?: number; // Denormalized
  // Auditing & Timestamps (Read-only on frontend)
  createdBy: ObjectId;
  updatedBy?: ObjectId;
  reviewedBy?: ObjectId;
  reviewComment?: string;
  reviewedAt?: Date | string;
  publishedAt?: Date | string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
}

/**
 * Represents a hydrated Mongoose document. On the frontend, this is often
 * identical to IProduct, but we keep it for consistency with the backend.
 */
export interface IProductDocument extends IProduct {
  _id: ObjectId; // In a document from the DB, _id is guaranteed.
}

/**
 * A lightweight, derived data structure for displaying products in lists or grids.
 * This is the shape of data returned by the `/products/list-items` endpoint.
 */
export interface IProductListItemData {
  _id: ObjectId;
  name: string;
  slug: string;
  currency: string;
  status: ProductStatus;
  visibility: ProductVisibility;
  tags?: string[];
  sellerType: "individual_seller" | "vendor";
  sellerId: ObjectId;
  // Derived or essential display fields
  mainImageUrl: string;
  displayPrice: number;
  displaySalePrice?: number;
  isOnSale: boolean;
  stockStatus: StockStatus;
  averageRating?: number;
  // Optional populated fields
  categoryName?: string;
  brandName?: string;
  // Link for client-side routing
  viewLink: string;
}

// --- Data Transfer Objects (DTOs) ---

/**
 * The shape of a file object when handled on the frontend before upload.
 * The buffer is not used on the client; instead, a File object is used.
 */
export type RawFile = File;

/**
 * DTO for creating a single product variation.
 * Image data is handled as an array of File objects.
 */
export interface CreateProductVariationDTO
  extends Omit<IProductVariation, "_id" | "imageUrls"> {
  imageFiles?: RawFile[]; // Array of raw image files for this variation
}

/**

 * DTO for creating a new product. This is the primary object used
 * to gather all information from a "Create Product" form.
 */
export type CreateProductDTO = Omit<
  IProduct,
  // Fields that are auto-generated by the backend or have special handling
  | "_id"
  | "slug"
  | "averageRating"
  | "reviewCount"
  | "publishedAt"
  | "createdAt"
  | "updatedAt"
  | "reviewedBy"
  | "reviewedAt"
  | "updatedBy"
  | "imageUrls" // Handled by `mainImageFiles`
  | "variations" // Handled by `variations` with CreateProductVariationDTO
  | "createdBy" // Set by the backend based on the authenticated user
> & {
  mainImageFiles?: RawFile[];
  variations: CreateProductVariationDTO[];
};

/**
 * DTO for updating an existing product. It's a partial of the main IProduct
 * interface, omitting fields that should not be updated via this route.
 */
export type UpdateProductDTO = Partial<
  Omit<
    IProduct,
    // Fields that are immutable or managed by other dedicated endpoints/processes
    | "_id"
    | "slug"
    | "sellerId"
    | "sellerType"
    | "createdBy"
    | "createdAt"
    | "updatedAt"
    | "averageRating" // Managed by review service
    | "reviewCount" // Managed by review service
  >
>;

