// src/types/product.ts

// --- Reusable Enums & Basic Types (Frontend Version) ---
export type ProductStatusFrontend =
  | "draft"
  | "pending_review"
  | "active"
  | "archived"
  | "rejected";

export type ProductVisibilityFrontend =
  | "public"
  | "hidden"
  | "private"; // Assuming this might be used, default 'hidden' for new

export type StockStatusFrontend =
  | "in_stock"
  | "out_of_stock"
  | "backorder"
  | "pre_order";

export type DimensionUnitFrontend = "cm" | "in" | "mm" | "m" | "ft" | "yd";
export type WeightUnitFrontend = "kg" | "g" | "lb" | "oz";

export interface IDimensionsForm { // For form state, allowing string for inputs
  length?: string | number; // Store as string from input, parse to number on submit
  width?: string | number;
  height?: string | number;
  unit?: DimensionUnitFrontend;
}

export interface IDimensionsPayload { // For API payload, ensuring numbers
  length?: number;
  width?: number;
  height?: number;
  unit?: DimensionUnitFrontend;
}


// --- Attribute Option Structure within a Variation (Frontend Form) ---
// This is what the ProductVariationsManager will build for each selected attribute option
export interface IProductAttributeOptionForm {
  attributeId: string;    // From selected IAttributeResponse.id
  attributeName: string;  // From selected IAttributeResponse.name
  optionId: string;       // From selected IAttributeOptionResponse.id
  optionValue: string;    // From selected IAttributeOptionResponse.value
  optionSwatchValue?: string; // From selected IAttributeOptionResponse.swatchValue
}

// --- Product Variation Structure (Frontend Form State) ---
export interface IProductVariationFormState {
  tempId: string; // Frontend-only temporary ID for new variations (e.g., `uuid()` or `temp-var-123`)
                  // For existing variations (in edit mode), this could map to backend's _id/id.
  sku: string;
  price: string; // Keep as string for form input, validate and parse to number on submit
  salePrice?: string;
  inventory: string;
  stockStatus: StockStatusFrontend;
  attributeOptions: IProductAttributeOptionForm[];

  // Image handling for this variation
  imageFiles: File[];          // New File objects selected for this variation
  existingImageUrls?: string[]; // URLs of already uploaded images (for edit mode)
  imagesToDelete?: string[];    // Public IDs or URLs of existing images to delete (for edit mode)

  weight?: string;
  weightUnit?: WeightUnitFrontend;
  dimensions?: IDimensionsForm;
  barcode?: string;
  costPrice?: string; // For admin input
  lowStockThreshold?: string;
  isActive: boolean; // Default to true for new variations
}

// --- Main Product Form State (for Create and Edit) ---
// This is the primary state object for ProductForm.tsx
export interface IProductFormState {
  id?: string; // Present if editing, undefined if creating

  name: string;
  // slug: string; // Generally auto-generated by backend, form might show a suggested one
  description: string;
  shortDescription: string;

  basePrice: string; // "Master" price, can be overridden by variations
  baseSalePrice?: string;
  currency: string;

  categoryId: string; // Selected category ID
  brandId?: string;    // Selected brand ID (optional)
  tags: string[];      // Managed as an array of strings, maybe from a tag input component

  // Main Product Images
  mainImageFiles: File[];          // New files for the main product
  existingMainImageUrls: string[]; // For displaying/managing current images
  mainImagesToDelete: string[];    // URLs or Public IDs of existing main images to delete

  sellerType: "individual_seller" | "vendor";
  sellerId: string; // Needs to be selected or determined

  status: ProductStatusFrontend;
  visibility: ProductVisibilityFrontend;

  variations: IProductVariationFormState[]; // Array of variations

  // SEO
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string[];

  // Shipping (default values for the product)
  defaultWeight: string;
  defaultWeightUnit?: WeightUnitFrontend;
  defaultDimensions: IDimensionsForm;
  isShippingRequired: boolean;

  // Compliance
  isHazardousMaterial: boolean;
  isAgeRestricted: boolean;
  ageRestrictionMinimum?: string;

  // Settings
  allowReviews: boolean;

  // Audit fields are typically not part of form state, set by backend/service
  // createdBy?: string;
  // updatedBy?: string;
}


// --- API Payload DTOs (mirroring backend CreateProductDTO but with frontend considerations) ---

// Structure for individual variation data sent to the backend
// Note: imageFiles are handled separately in FormData, not directly in this JSON part
export interface IProductVariationPayloadDTO extends Omit<IProductVariationFormState, 'tempId' | 'imageFiles' | 'existingImageUrls' | 'imagesToDelete'> {
  _id?: string; // For backend to identify existing variations during an update. New variations won't have this.
  // Numeric fields converted from form state strings
  price: number;
  salePrice?: number;
  inventory: number;
  weight?: number;
  costPrice?: number;
  lowStockThreshold?: number;
  dimensions?: IDimensionsPayload; // Use numeric dimensions payload
  // attributeOptions: IProductAttributeOptionForm[]; // This is already correct
}

// This is what the backend CreateProductDTO more or less expects for the JSON part of FormData
export interface IProductCreatePayloadDTO extends Omit<IProductFormState, 'id' | 'mainImageFiles' | 'existingMainImageUrls' | 'mainImagesToDelete' | 'variations'> {
  // Numeric fields converted from form state strings
  basePrice: number;
  baseSalePrice?: number;
  defaultWeight?: number;
  ageRestrictionMinimum?: number;
  variations: IProductVariationPayloadDTO[]; // Array of processed variations
  // slug might be sent if user explicitly sets it and backend allows overriding auto-generation
  slug?: string;
}

// For Update, it's similar but most fields are Partial.
// The handling of variations (create, update, delete existing) and images (add new, delete existing)
// needs to be carefully managed when constructing FormData for an update.
export interface IProductUpdatePayloadDTO extends Partial<IProductCreatePayloadDTO> {
  // Special handling for arrays that need full replacement vs. partial update
  // might be needed, or backend handles diffing.
  // For simplicity, assume similar structure for update, backend diffs.
  imageUrls?: string[]; // Potentially the new set of main image URLs after additions/deletions
}


// --- API Response Types (What we get back from the backend) ---
// This IProductResponse should match the one from your attribute.types.ts if structure is same,
// or be specific if product responses differ. Let's assume it's the same as IProductResponse
// defined for Attributes, but tailored for Product.

// Structure for a single variation object received from the API
export interface IProductVariationResponse {
  id: string; // or _id: string
  sku?: string;
  price: number;
  salePrice?: number;
  inventory: number;
  stockStatus: StockStatusFrontend;
  attributeOptions: IProductAttributeOptionForm[]; // Assuming backend returns this populated
  imageUrls?: string[];
  mainVariationImageIndex?: number;
  weight?: number;
  weightUnit?: WeightUnitFrontend;
  dimensions?: IDimensionsPayload; // Expect numbers from API
  barcode?: string;
  costPrice?: number;
  lowStockThreshold?: number;
  isActive: boolean;
}

// Main product response from API
export interface IProductResponse {
  id: string; // or _id
  name: string;
  slug: string;
  description?: string;
  shortDescription?: string;
  basePrice?: number;
  baseSalePrice?: number;
  currency: string;
  categoryId: string;
  categoryName?: string; // Denormalized, if backend provides
  brandId?: string;
  brandName?: string; // Denormalized
  tags?: string[];
  imageUrls: string[];
  mainProductImageIndex?: number;
  sellerType: "individual_seller" | "vendor";
  sellerId: string;
  sellerName?: string; // Denormalized
  status: ProductStatusFrontend;
  visibility: ProductVisibilityFrontend;
  variations: IProductVariationResponse[]; // Uses the response type for variations
  metaTitle?: string;
  metaDescription?: string;
  metaKeywords?: string[];
  defaultWeight?: number;
  defaultWeightUnit?: WeightUnitFrontend;
  defaultDimensions?: IDimensionsPayload;
  isShippingRequired: boolean;
  isHazardousMaterial: boolean;
  isAgeRestricted: boolean;
  ageRestrictionMinimum?: number;
  allowReviews: boolean;
  averageRating?: number;
  reviewCount?: number;
  createdBy: string; // User ID string
  updatedBy?: string;
  publishedAt?: string; // ISO Date string
  createdAt: string;   // ISO Date string
  updatedAt: string;   // ISO Date string
  // displayPriceInfo?: any; // From backend virtual
}

// Re-export or define generic API response types if not already global
// export interface ApiResponse<T> { ... }
// export interface IPaginatedData<T> { ... }